# Generated by Django 5.0.2 on 2024-03-05 18:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('mobile_no', models.CharField(max_length=15)),
                ('dob', models.DateField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=25)),
                ('selling_price', models.IntegerField()),
                ('discounted_price', models.IntegerField()),
                ('desc', models.CharField(max_length=200)),
                ('product_image', models.ImageField(upload_to='uploads/to')),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='testapp4.category')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.BooleanField(default='False')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp4.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp4.product')),
            ],
        ),
    ]
